FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY GITP.API/GITP.API.csproj GITP.API/
RUN dotnet restore GITP.API/GITP.API.csproj
COPY . .
RUN dotnet publish GITP.API/GITP.API.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 80
ENTRYPOINT ["dotnet", "GITP.API.dll"]
